### ISSUE TITLE
getStaticProps,getServerProps 사용에 문제가 있다.

### ISSUE THREAD

**Issue by TypingOK** [TypingOK/omega-consumer#3]
서버 렌더링을 통해서 미리 데이터를 얻어오려고 시도 하지만 성공 할 수 없었다.
대신에 useEffect를 사용해서 비슷하게 적용 했지만 완벽한 정답은 아님.
getStaticProps,getServerProps로 바꾸려면 어떻게 해야할까?

https://github.com/StartPlayUp/omega-consumer/blob/jin/components/homePageContainer/contents/homePageContents.jsx

**Comment by jsc7727** [comment]
미리 데이터를 받아오는 것이 정답은 아니다.
매번 갱신 되는 데이터일 경우 serversideprops, 뉴스 기사나 블로그 글 같이 잘 바뀌지 않는 글은 getStaticProps를 사용해야 한다.
