### ISSUE TITLE
Ant-디자인 문제

### ISSUE THREAD

**Issue by TypingOK** [TypingOK/omega-consumer#7]
ant 디자인을 적용하기 위해
`import "antd/dist/antd.css";` 를 했습니다.
하지만 의도와는 다르게 로고와 공지사항까지 파란색으로 나오는 문제가 발생하였습니다.
![image](https://user-images.githubusercontent.com/38030774/144853869-a2a023a1-62eb-45a9-898e-f573e2d67f28.png)

**Comment by jsc7727** [comment]
![image](https://user-images.githubusercontent.com/20225380/145404912-952c9ac4-453f-4637-b61d-71ac1527d64e.png)
![image](https://user-images.githubusercontent.com/20225380/145404991-d8ed9e70-229f-445d-a672-ac3299c0347f.png)
![image](https://user-images.githubusercontent.com/20225380/145405639-0a17c09e-f761-4030-bb48-e47462f154a3.png)

next/link는 <a></a> 태그가 자동으로 생성됩니다.
antd.css 가 전역으로 들어가게 끔 설정된 상태이기에 <a></a> 태그는 --ant-primary-color로 설정됩니다.

해결 방법으로는 
1. 강제로 적용 link 태그 아래 a태그가 생기니 직접 생성 해주고 style을 지정해주면 됩니다.
2. 공식 문서를 보고 웹팩 설정을 통해 해당 값을 바꿔주면 됩니다. - https://ant.design/docs/react/customize-theme
