### ISSUE TITLE
next/image  모듈 사용할 때 외부 호스트

### ISSUE THREAD

**Issue by TypingOK** [TypingOK/omega-consumer#8]
https://nextjs.org/docs/messages/next-image-unconfigured-host

```
  images: {
    domains: ["cdn.discordapp.com"],
  },
```
next/image 모듈을 사용하기 위해 디스코드에 업로드 한 이미지를 사용하기 위해 위 링크에 있는 방법을 사용함

**Comment by jsc7727** [comment]
확인했습니다.
