### ISSUE TITLE
상수가 제대로 import 되지 않음, 동적 라우팅 문제

### ISSUE THREAD

**Issue by TypingOK** [TypingOK/omega-consumer#9]
상수를 사용하려는 곳에서 import 하였으나 undefinded가 뜸

처음 헤더를 통해 동적라우팅으로 들어온 경우 정상적으로 작동 하지만
글쓰기를 누른 후 헤더를 통해 다른 게시판으로 넘어가려는 경우
동적 라우팅이 정상적으로 동작하지 않고 다시 메인 페이지로 돌아갑니다.

**Comment by jsc7727** [comment]
![image](https://user-images.githubusercontent.com/20225380/146210090-abc70b70-12f4-46ee-b6f7-8a5c786a4729.png)
tsconfig 설정에 해당 경로가 없기에 문제가 발생하였습니다. 
해당 경로를 넣어주면 정상 작동합니다.
